version: '2'
services:
    web:
        build: .
        environment:
            - REDIS_HOST=redis
            - DB_HOST=mongodb
        container_name: "web"
        ports:
            - 5000:5000
        depends_on:
            - mongodb
            - redis
        command: [ "python", "main.py" ]
    mongodb:
        image: "mongo"
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: ["mongod"]
    redis:
        image: "redis:alpine"
        container_name: "redis"
        ports:
            - 6379:6379
        command: redis-server
