version: '2'
services:
    web:
        build: .
        container_name: "web"
        depends_on:
            - db
            - redis
        command: ["./start_mongo.sh", "db", "--", "python", "main.py"]
    db:
        image: "mongo"
        container_name: "mongodb"
        ports:
            - 27017:27017
    redis:
        image: "redis:alpine"
        container_name: "redis"
        ports:
            - 6379:6379
        command: redis-server
